name: rider
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.27.5
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  google_maps_flutter: ^2.1.8
  geolocator: ^9.0.1
  http: ^0.13.4
  provider: ^6.0.3
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.1.0
  custom_info_window: ^1.0.1
  intl: ^0.17.0
  flutter_typeahead: ^4.0.0
  google_maps_cluster_manager: ^3.0.0+1
  firebase_messaging: ^11.4.4
  maps_toolkit: ^2.0.0
  flutter_lints: ^2.0.1
  flutter_svg: any
  dio: ^4.0.1
  location: ^4.3.0
  bot_toast: ^4.0.2
  connectivity: ^3.0.6
  shared_preferences: ^2.0.8
  clippy_flutter: ^2.0.0-nullsafety.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  equatable: ^2.0.3
  get_it: ^7.2.0
  retry_bot: ^1.0.1
  lottie: ^1.2.1
  get: ^4.6.5
  either_dart: ^0.1.4
  internet_connection_checker: ^0.0.1+4
  dotted_line: ^3.1.0
  about: ^2.1.0
  flutter_animarker: ^3.2.0
  flutter_bounce: ^1.1.0
  signalr_netcore: ^1.3.1
  core:
    path: packages/core
  design:
    path: packages/design
  network:
    path: packages/network
  moor: ^4.4.0
  search_choices: ^2.1.1
  moor_flutter: ^4.1.0
  flutter_slider_drawer: ^2.1.1
  rating_dialog: ^2.0.4
  image_picker: ^0.8.4+11
  awesome_dialog: ^2.2.1
  custom_marker: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  dependency_validator: ^3.0.0
  moor_generator: ^4.4.1
  freezed: any
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/intro/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - README.md
    - lotti_files/

  fonts:

    - family: sst-arabic
      fonts:
        - asset: assets/fonts/sst_arabic_bold.ttf
        - asset: assets/fonts/sst_arabic_light.ttf
        - asset: assets/fonts/sst_arabic_medium.ttf
        - asset: assets/fonts/sst_arabic_roman.ttf