name: driver
description: This is Drivers App Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.17.0
  awesome_dialog: ^2.2.1
  firebase_auth: ^3.3.18
  google_maps_flutter: ^2.1.8
  geolocator: ^9.0.1
  http: ^0.13.4
  provider: ^6.0.2
  dotted_line: ^3.1.0
  units_converter: ^2.0.1
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.1.2
  flutter_animarker: ^3.2.0
  intl: ^0.17.0
  firebase_messaging: ^11.4.0
  maps_toolkit: ^2.0.0
  flutter_lints: ^2.0.1
  easy_localization: ^3.0.1
  package_info: ^2.0.2
  flutter_svg: any
  dio: ^4.0.1
  location: ^4.4.0
  bot_toast: ^4.0.2
  shared_preferences: ^2.0.15
  google_maps_webservice: ^0.0.20-nullsafety.5
  equatable: ^2.0.3
  get_it: ^7.2.0
  retry_bot: ^1.0.1
  lottie: ^1.2.1
  get: ^4.6.3
  either_dart: ^0.1.4
  internet_connection_checker: ^0.0.1+4
  cached_network_image: ^3.2.1
  flutter_bounce: ^1.1.0
  signalr_netcore: ^1.3.0
  about: ^2.1.0
  sliding_up_panel: ^2.0.0+1
  image_picker: ^0.8.4+11
  http_parser: ^4.0.1
  smooth_star_rating_null_safety: ^1.0.4+2
  responsive_framework: ^0.2.0
  search_choices: ^2.1.1
  permission_handler: ^10.0.0
  core:
    path: packages/core
  design:
    path: packages/design
  network:
    path: packages/network
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  freezed: any
flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/intro/
     - assets/images/
     - assets/icons/
     - assets/lottie/
     - README.md
     - lotti_files/

  fonts:
    - family: sst-arabic
      fonts:
        - asset:  assets/fonts/sst_arabic_bold.ttf
        - asset:  assets/fonts/sst_arabic_light.ttf
        - asset:  assets/fonts/sst_arabic_medium.ttf
        - asset:  assets/fonts/sst_arabic_roman.ttf
